[package]
name = "gatekeeper"
version = "0.1.0"
authors = ["Adam Piekarczyk <adam1piekarczyk@gmail.com>"]

[dependencies.config]
git = "https://github.com/filipegoncalves/rust-config"
rev = "beed106c745929824a5e3c58c15a33ce32afb257"

[dependencies]
postgres = "~0.9.6"
rust-crypto = "~0.2.31"